# Generated by Django 4.0.4 on 2022-04-27 06:15

from django.db import migrations, models
import stripeapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('stripeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=stripeapp.models.Product.nameFile),
        ),
    ]
